### PR TITLE
fix: Logic lab not registered

### PR DESCRIPTION
**Pull request by bukandicki**
### JIRA Link
N/A
### Changelog / Description
-Fix Logic lab not registered

### CODE REVIEW

**Comment by hilyds** [comment]
pending for a while, do not merge this PR first. we're still thinking which one is better, to validate cannot delete service if service count = 1 or the other way

**Comment by bukandicki** [comment]
alright, please let me know if there's anything I can help you with

**Comment by bukandicki** [comment]
Hi, mbak @hilyds, is there an update regarding this issue? if there is, please let me know 😉

**Comment by hilyds** [comment]
I close this PR because it's no longer relevant, as the new validation and flow is currently on progress @bukandicki. Thank you!

**Pull request closed without merging**
