### PR TITLE
feat: mixpanel and sentry analytics.

### PR DESCRIPTION
**Pull request by agustinustheo**
### JIRA LINK 
- https://blocksphere2020.atlassian.net/browse/DBIO-1421

### Changelog/Description
- Setup app analytics with Mixpanel.
- Sentry for crashlytics.

### WARNING ⚠️
- Must add `VUE_APP_SENTRY_DSN` and `VUE_APP_MIXPANEL_TOKEN` environment variable, accessible here: https://blocksphere2020.atlassian.net/wiki/spaces/DBIO/pages/33063034/Frontend+ENV

### CODE REVIEW

**Review by bukandicki — APPROVED** [review]
Looks good, just some nitpicks. Can we use `console.error` for error instead of using `console.log`?

**Comment by agustinustheo** [comment]
> Looks good, just some nitpicks. Can we use `console.error` for error instead of using `console.log`?

No problem, but notice that I didn't add that `console.log` in. I just simply replaced the quotes to double-quotes.

**Comment by agustinustheo** [comment]
Next sprint, we can make a separate logging library in the `common` folder @bukandicki this folder will handle all the console logs and errors. And will connect to both Mixpanel and Sentry.

**Comment by bukandicki** [comment]
OK, btw I'm just curious about this env, did you intentionally leave it blank by not filling in the value there? 😁
image

**Comment by agustinustheo** [comment]
> 

You can ask @irmannmal for the value

**Pull request merged**
