### PR TITLE
[ Update ] Layout on EMR page

### PR DESCRIPTION
**Pull request by bukandicki**
### JIRA LINK
https://blocksphere2020.atlassian.net/browse/DBIO-319

### FIGMA LINK
https://www.figma.com/file/zl3qPAORY04CoGl1v5gSHw/DeBio-Web-App?node-id=1530%3A0

### Changelog/Description
Minor update some layout on the EMR page

### BLOCKER/QUESTION
Hi, guys, I have a question, I hope you are can help me, I have no idea to handle this layout. Have you ever got an error when uploading a file directly (pending file)? (before it is sent to the server). I think if I upload files one by one directly to the server without pending files first it's not possible, because on the last step there will be a re-confirmation dialog. And the second problem is if I upload directly to the server is when users refresh the page and they do not confirm the dialog on the last step it will still be uploaded to the server, any idea guys? Thanks in advance

image

### CODE REVIEW

**Review by agustinustheo — APPROVED** [review]

**Comment by agustinustheo** [comment]
@bukandicki No, it is not possible to add encryption to the files after upload because DeBio uploads directly to IPFS. So the UI would need to change, please report it to the UI/UX designer or mention this during our daily standup. Anyway, the code looks good. Nice job either way.

**Comment by bukandicki** [comment]
Hi, @agustinustheo thanks for your answer to this PR question. if that's the case, then I'll try to discuss this with the UI/UX team 😉

**Comment by bukandicki** [comment]
Oh hi, @agustinustheo. Anyway, can I merge this PR now? Or should I wait for feedback from the UI/UX team first?

**Comment by agustinustheo** [comment]
If you feel the feature is still usable enough you may squash and merge, don't forget to delete your branch though. @bukandicki 

Otherwise, wait for the UI/UX team's response, please.

**Pull request merged**
