### PR TITLE
add field for DNA collection process on add service lab

### PR DESCRIPTION
**Pull request by luthfiazhari**
### JIRA Link
[https://blocksphere2020.atlassian.net/browse/DBIO-998](url)
[https://blocksphere2020.atlassian.net/browse/DBIO-999](url)

### Changelog / Description
- Add new dna_collection_process field in Services registration form.
- Add new dna_collection_process field in Services edit form.

### CODE REVIEW

**Comment by luthfiazhari** [comment]
tinggal dibagian edit service belom bambahin field type of biological sample

**Review by agustinustheo — CHANGES_REQUESTED** [review]
Please add the PR description.

**Comment by luthfiazhari** [comment]
@agustinustheo sorry i forgot to add PR description

**Review by agustinustheo — APPROVED** [review]
LGTM, but there are conflicts that needs fixing @luthfiazhari .

**Comment by luthfiazhari** [comment]
> Please add the PR description.

I've added a description for this PR

**Comment by luthfiazhari** [comment]
i've alredy solve conflicts for this PR

**Review by agustinustheo — APPROVED** [review]
LGTM!

**Pull request merged**
